import './index.css'
export  {default as Header} from './header'
export  {default as Banner} from './banner'
export  {default as Main} from './main/index'
export  {default as Visit} from './visit'
export  {default as Show} from './show'
export  {default as Footer} from './footer'
export  {default as SignIn} from './signIn'
export  {default as PersonalData} from './personal'
export  {default as Page404} from './page404'
export  {default as Administrator} from './administrator'
export  {default as Register} from './register'
export  {default as Business} from './business'
export  {default as Service} from './service'
