import './index.css'
export  {default as Header} from './header'
export  {default as Banner} from './banner'
export  {default as Main} from './main/index'
export  {default as Visit} from './visit'
export  {default as Footer} from './footer'